import { BlogTagComponent } from './../../../../shared/components/blog-tag/blog-tag.component';
import { Component, HostListener, OnInit, OnDestroy, AfterViewInit, Inject, PLATFORM_ID } from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { AnimatedButton } from '@components/animated-button/animated-button.component';
import { Router, RouterLink, ActivatedRoute, NavigationEnd } from '@angular/router';
import { NewsComponent } from '@components/news/news.component';
import { Meta } from '@angular/platform-browser';
import { Subscription, filter } from 'rxjs';
import { ButtonComponent } from '@components/button/button.component';
import { blogList } from '../blogList';

@Component({
  selector: 'app-heatsink',
  standalone: true,
  imports: [
    BlogTagComponent,
    CommonModule,
    AnimatedButton,
    RouterLink,
    NewsComponent,
    ButtonComponent
  ],
  templateUrl: './heatsink.component.html',
})
export class HeatsinkComponent implements OnInit, AfterViewInit, OnDestroy {
  blogs = blogList;

  tags = ['Whitepaper', 'Thermal Management', 'Cooling Solutions'];

  factors = ['Surface area', 'Material choice', 'Fin geometry', 'Base dimensions', 'Innovative elements like varying sizes, scales, and protrusions'];

  approaches = [
    {
      number: '01',
      desc: 'Optimal fin spacing and number of fins are crucial for maximum heat transfer. Thinner fins improve performance by allowing more fins per base plate, while fin height and length significantly affect heatsink conductance and temperature regulation. The results indicate that careful consideration of fin dimensions can lead to an efficient heatsink design that meets specific thermal performance requirements [8]'
    },
    {
      number: '02',
      desc: 'Perforated pinned heatsinks improve CPU temperature, fan power consumption, heat transfer rate, and positioning of perforations plays a significant role. Perforated heatsinks are lighter and more efficient for cooling electronic devices and systems [10].'
    }
  ];

  rules = [
    {
      number: '01',
      desc: 'Thermal interface materials (TIMs) play a critical role in efficient heat transfer. TIMs bridge microscopic gaps and imperfections between mating surfaces, ensuring a low-resistance thermal pathway for heat dissipation. Use TIM to enhance thermal conductivity.'
    },
    {
      number: '02',
      desc: 'Mount fins in the vertical plane for optimum natural convective cooling. Do not overcrowd or obstruct devices.'
    },
    {
      number: '03',
      desc: 'Do not block airflow around heatsinks, particularly directly above and below items that rely on natural convection.'
    },
    {
      number: '04',
      desc: 'If thermal demands are particularly high, consider using forced convection.'
    }
  ];

  selections = [
    {
      number: '01',
      desc: '<b>Determine Heat Generation:</b> Calculate the amount of heat, Q, generated by the device in watts (W).'
    },
    {
      number: '02',
      desc: '<b>Device & Ambient Temperatures:</b> Identify maximum junction temperature and ambient air temperature.'
    },
    {
      number: '03',
      desc: '<b>Convection Type:</b> Identify whether cooling is natural or forced. For forced convection, know air flow velocity (LFM).'
    },
    {
      number: '04',
      desc: `<b>Calculate Thermal Resistance:</b> Thermal Resistance = (Tj - Ta) / Q`
    }
  ];

  infos = [
    { number: '01', desc: '<a href="https://scispace.com/papers/heat-generation-by-electrical-current-in-a-quantum-dot-3q31r4apiq" target="_blank" class="underline">Heat Generation by Electrical Current in a Quantum Dot Hybridized to Majorana Nanowires</a>' },
    { number: '02', desc: '<a href="https://scispace.com/papers/synthetic-jet-based-hybrid-heat-sink-for-electronic-cooling-27one3q0tw" target="_blank" class="underline">Synthetic Jet-Based Hybrid Heatsink for Electronic Cooling<a/>' },
    { number: '03', desc: '<a href="https://scispace.com/papers/the-effects-of-heat-on-electronic-components-1xf86liwi2" target="_blank" class="underline">The Effects of Heat on Electronic Components<a/>' },
    { number: '04', desc: '<a href="https://scispace.com/papers/heat-sinks-1a7mwr8x" target="_blank" class="underline">Heatsinks<a/>' },
    { number: '05', desc: '<a href="https://scispace.com/papers/heat-sinks-1a7mwr8x" target="_blank" class="underline">Electronic device with integrated passive and active cooling<a/>' },
    { number: '06', desc: '<a href="https://www.finskiving.com/heat-sink-manufacturing-technologies/heat-sink-design-and-selection" target="_blank" class="underline">Heat Sink Manufacturing Guide<a/>' },
  ];

  cards = [
    {
      imageUrl: 'assets/news/blogs/blog-bottom/5g.png',
      link: '/news-&-insights/whitepaper-5g-oru',
      tags: ['Case Study', 'Hardware Design', 'Telecom Engineering'],
      date: 'September 05, 2020',
      title: 'Building the Future of 5G Connectivity with Open Radio Unit Solutions',
    },
    {
      imageUrl: 'assets/news/blogs/blog-bottom/invensify.png',
      link: '/news-&-insights/whitepaper-invensify',
      tags: ['Case Study', 'Medical Devices'],
      date: 'December 12, 2024',
      title: 'Developing Smart Medical Devices: The Invensify Case Study',
    },
    {
      imageUrl: 'assets/news/blogs/blog-bottom/pcle6.png',
      link: '/news-&-insights/whitepaper-pcle6',
      tags: ['Heatsink', 'Thermal Management'],
      date: 'May 29, 2024',
      title: 'PCIe-6: Everything You Need To Know',
    }
  ];

  private fragmentSubscription!: Subscription;
  private navigationSubscription!: Subscription;
  currentFragment: string | null = null;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private meta: Meta,
    @Inject(PLATFORM_ID) private platformId: Object
  ) { }

  ngOnInit(): void {
    if (isPlatformBrowser(this.platformId)) {
      // Update meta tags
      this.route.data.subscribe(() => {
        const url = encodeURIComponent(window.location.href);
        this.meta.updateTag({ property: 'og:url', content: url });
      });
    }

    // Fragment handling
    this.fragmentSubscription = this.route.fragment.subscribe((fragment) => {
      if (isPlatformBrowser(this.platformId) && fragment) {
        this.currentFragment = fragment;
        this.scrollToCategory(fragment);
      }
    });

    this.navigationSubscription = this.router.events
      .pipe(filter(event => event instanceof NavigationEnd))
      .subscribe(() => {
        if (isPlatformBrowser(this.platformId)) {
          const fragment = this.route.snapshot.fragment;
          if (fragment && fragment !== this.currentFragment) {
            this.currentFragment = fragment;
            this.scrollToCategory(fragment);
          }
        }
      });
  }

  ngAfterViewInit(): void {
    if (isPlatformBrowser(this.platformId)) {
      const links = document.querySelectorAll('.link-to-power');
      links.forEach((link) => {
        link.addEventListener('click', () => {
          this.router.navigate(['/services/engineering-design/power-delivery-network-simulation']);
        });
      });
    }
  }

  ngOnDestroy(): void {
    this.fragmentSubscription?.unsubscribe();
    this.navigationSubscription?.unsubscribe();
  }

  @HostListener('window:scroll', [])
  onScroll(): void {
    if (!isPlatformBrowser(this.platformId)) return;

    const sections = Array.from({ length: 14 }, (_, i) => `section${i + 1}`);
    const headerOffset = 500;

    for (const id of sections) {
      const el = document.getElementById(id);
      if (el) {
        const rect = el.getBoundingClientRect();
        const adjustedTop = rect.top - headerOffset;
        if (adjustedTop <= 0 && rect.bottom > headerOffset) {
          this.currentFragment = id;
          break;
        }
      }
    }
  }

  scrollToCategory(id: string): void {
    if (!isPlatformBrowser(this.platformId)) return;
    this.currentFragment = id;

    const el = document.getElementById(id);
    if (el) {
      const offset = window.innerHeight * 0.42;
      window.scrollTo({ top: el.offsetTop - offset, behavior: 'smooth' });
    }
  }

  isActive(id: string): boolean {
    return this.currentFragment === id;
  }

  shareOnFacebook(): void {
    if (!isPlatformBrowser(this.platformId)) return;
    const url = encodeURIComponent(window.location.href);
    window.open(`https://www.facebook.com/sharer/sharer.php?u=${url}`, '_blank');
  }

  shareOnTwitter(): void {
    if (!isPlatformBrowser(this.platformId)) return;
    const pageUrl = window.location.href;
    const text = encodeURIComponent(
      `🚀 Discover Heatsink by Whizz Systems!\n\nHeatsinks: Considerations, guidance, and best practices.\n\nProudly built by @whizzsystems.\n\n`
    );
    const hashtags = encodeURIComponent('whizzsystems,ThermalManagement,AISystemThermal');
    window.open(`https://twitter.com/intent/tweet?text=${text}&hashtags=${hashtags}&url=${encodeURIComponent(pageUrl)}`, '_blank');
  }

  shareOnLinkedIn(): void {
    if (!isPlatformBrowser(this.platformId)) return;
    const url = encodeURIComponent(window.location.href);
    window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${url}`, '_blank');
  }
}
